### ISSUE TITLE
extract tarball

### ISSUE THREAD

**Issue by JABAGAMEHUNTER** [calebolson123/DogPoopDetector#2]
Hello man
So, i wanted to download the tarball but it keeps showing an error when i try using tar -xfv [name of the file.tar.gz]
It says 

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

when i use command file to see the extension of the compressed file it returns:
DLC_SecurityCamPooping_resnet_50_iteration-0_shuffle-1.tar.gz: ASCII text

what can i do? If i am trying something wrong please let me know, thanks.

**Comment by zoltanszalontay** [comment]
The model is 178M so it's stored in git lfs. Therefore you have to install lfs. 
More info: https://git-lfs.com/
